library(ipw)
library(survey)
data = read.csv("data/tidy_data.csv")
temp <- ipwpoint(exposure = Uninsured, family="gaussian", numerator=~1, denominator=~dem08_frac2+dem12_frac2+rep08_frac2+rep12_frac2+Median.Earnings.2010.dollars+Poverty.Rate.below.federal.poverty.threshold+Management.professional.and.related.occupations+Service.occupations+Sales.and.office.occupations+Farming.fishing.and.forestry.occupations+Construction.extraction.maintenance.and.repair.occupations+Unemployment, data = data) 
summary(temp$ipw.weights)
ipwplot(weights = temp$ipw.weights, logscale = FALSE, main = "Stabilized weights", xlim = c(0, 8))
data$sw <- temp$ipw.weights
msm <- (svyglm(rep16_frac2 ~ Uninsured, design = svydesign(~ 1, weights = ~sw, data = data)))
coef(msm)
confint(msm)